version: '3.1'

services:

  db:
    image: ajeena/mydb:1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPass1234
      MYSQL_USER: archana
      MYSQL_DATABASE: orderdb
      MYSQL_PASSWORD: pass1234

  adminer:
    image: adminer
    restart: always
    environment:
      DBURL: archana
      DBNAME: orderdb
      DBUSER: archana
      DBPASS: pass1234
    ports:
      - 8080:8080